In [1]:
from demoparser2 import DemoParser

Team 1 Score
Team 2 Score
All Players 1...5 Kills|Deaths|Assists|Rating 2.0|Cash at round start
Current map
First half or second half

In [5]:
parser = DemoParser("demos\\iem-katowice-2025-vitality-vs-3dmax-bo3-KNzbDELEQ75v8nvhNNs8tI\\vitality-vs-3dmax-m1-inferno.dem")

In [13]:
wanted_ticks = parser.parse_event("round_freeze_end")["tick"].tolist()
df = parser.parse_ticks(["current_equip_value", 
                         "total_rounds_played",
                         "kills_total",
                         "deaths_total",
                         "assists_total",
                         "damage_total",
                         "team_rounds_total",
                         "team_clan_name",
                         "balance"
                         ], ticks=wanted_ticks)
df.to_csv('gamedata.csv', index='tick')
df

,total_rounds_played,balance,kills_total,deaths_total,assists_total,damage_total,current_equip_value,team_rounds_total,team_clan_name,tick,steamid,name
0,0,150,0,0,0,0,1450,0,3DMAX,1263,76561198031890115,Lucky
1,0,150,0,0,0,0,850,0,3DMAX,1263,76561198179538505,Graviti
2,0,150,0,0,0,0,850,0,Team Vitality,1263,76561197973140692,mezii
3,0,150,0,0,0,0,950,0,Team Vitality,1263,76561198113666193,ZywOo
4,0,150,0,0,0,0,850,0,3DMAX,1263,76561198047876970,Djoko
...,...,...,...,...,...,...,...,...,...,...,...,...
345,34,4800,19,26,6,2247,5100,18,Team Vitality,286708,76561197989744167,apEX
346,34,4600,22,24,7,2998,5100,18,Team Vitality,286708,76561197978835160,flameZ
347,34,6300,22,22,6,2126,7950,16,3DMAX,286708,76561198045739761,Maka
348,34,4400,21,20,4,2464,5100,18,Team Vitality,286708,76561197991272318,ropz
349,34,8350,30,22,7,3015,6100,16,3DMAX,286708,76561198168198200,Ex3rcice

In [7]:
event_df = parser.parse_event("player_death", player=["X", "Y"], other=["total_rounds_played"])
event_df

,assistedflash,assister_X,assister_Y,assister_name,assister_steamid,attacker_X,attacker_Y,attacker_name,attacker_steamid,attackerblind,...,total_rounds_played,user_X,user_Y,user_name,user_steamid,weapon,weapon_fauxitemid,weapon_itemid,weapon_originalowner_xuid,wipe
0,False,2128.291992,-149.018677,Ex3rcice,76561198168198200,1828.966064,127.088432,Lucky,76561198031890115,False,...,0,2573.139160,-150.982483,mezii,76561197973140692,inferno,,,,0
1,False,NaN,NaN,None,None,1819.245361,274.391357,ZywOo,76561198113666193,False,...,0,2139.466309,157.710419,Graviti,76561198179538505,elite,17293822569105784834,11081995323,,0
2,False,1964.710449,88.976852,Lucky,76561198031890115,2341.421143,-230.219666,Ex3rcice,76561198168198200,False,...,0,2065.779541,613.392761,apEX,76561197989744167,glock,17293822569105850372,41234570836,,0
3,False,NaN,NaN,None,None,2366.469482,-149.356812,Ex3rcice,76561198168198200,False,...,0,1845.911499,311.118134,ZywOo,76561198113666193,glock,17293822569105850372,41234570836,,0
4,False,NaN,NaN,None,None,1051.563232,587.680115,ropz,76561197991272318,False,...,1,694.127258,-64.593140,Ex3rcice,76561198168198200,famas,17293822569127018506,26819094551,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,False,429.446411,1863.793701,Djoko,76561198047876970,862.008057,2232.409912,Graviti,76561198179538505,False,...,34,348.929199,1974.040649,mezii,76561197973140692,hegrenade,,,,0
231,False,NaN,NaN,None,None,864.637390,2221.679932,Graviti,76561198179538505,False,...,34,343.367706,1933.365356,ZywOo,76561198113666193,ak47,17293822569150152711,30576196202,,0
232,False,343.297821,1933.503784,ZywOo,76561198113666193,405.396698,1782.753540,apEX,76561197989744167,False,...,34,876.570374,2155.770020,Graviti,76561198179538505,ak47,17293822569179447303,40315850357,,0
233,False,350.208984,1973.981934,mezii,76561197973140692,828.237183,2356.988281,flameZ,76561197978835160,False,...,34,547.651001,2617.641113,Maka,76561198045739761,ak47,17293822569150152711,30576196202,,0
234,False,NaN,NaN,None,None,860.362549,2285.011719,ropz,76561197991272318,False,...,34,369.840271,1853.793823,Ex3rcice,76561198168198200,ak47,17293822569114501127,24095176570,,0

Convert the extracted data into a more usable version (wider), one for each round.

In [14]:
import pandas as pd
df = pd.read_csv('gamedata.csv')

In [40]:
[f"player_{i}" for i in range(1,11)]

['player_1',
 'player_2',
 'player_3',
 'player_4',
 'player_5',
 'player_6',
 'player_7',
 'player_8',
 'player_9',
 'player_10']

In [18]:
df

,tick,total_rounds_played,balance,kills_total,deaths_total,assists_total,damage_total,current_equip_value,team_rounds_total,team_clan_name,steamid,name
0,1263,0,150,0,0,0,0,1450,0,3DMAX,76561198031890115,Lucky
1,1263,0,150,0,0,0,0,850,0,3DMAX,76561198179538505,Graviti
2,1263,0,150,0,0,0,0,850,0,Team Vitality,76561197973140692,mezii
3,1263,0,150,0,0,0,0,950,0,Team Vitality,76561198113666193,ZywOo
4,1263,0,150,0,0,0,0,850,0,3DMAX,76561198047876970,Djoko
...,...,...,...,...,...,...,...,...,...,...,...,...
345,286708,34,4800,19,26,6,2247,5100,18,Team Vitality,76561197989744167,apEX
346,286708,34,4600,22,24,7,2998,5100,18,Team Vitality,76561197978835160,flameZ
347,286708,34,6300,22,22,6,2126,7950,16,3DMAX,76561198045739761,Maka
348,286708,34,4400,21,20,4,2464,5100,18,Team Vitality,76561197991272318,ropz
349,286708,34,8350,30,22,7,3015,6100,16,3DMAX,76561198168198200,Ex3rcice

In [44]:
list(df['name'].unique())

['Lucky',
 'Graviti',
 'mezii',
 'ZywOo',
 'Djoko',
 'apEX',
 'flameZ',
 'Maka',
 'ropz',
 'Ex3rcice']

In [56]:
df = pd.read_csv('gamedata.csv')
# df = df.drop(columns=['steamid'])
team_fields = ['']
suffix_list = [f"player_{i}" for i in range(1,11)]
df['player_name'] = df['name'].replace(dict(zip(list(df['name'].unique()),suffix_list)))
df = df.pivot(index=['tick','total_rounds_played',''], columns=['player_name'])
df

                            balance                                       \
player_name                player_1 player_10 player_2 player_3 player_4
tick   total_rounds_played
1263   0                        150       100      150      150      150
8696   1                          0         0      200      150      100
18447  2                        250      1150      350     1800     1800
26997  3                       2500      1300     3600        0       50
35957  4                          0       400      100     2150     1000
43304  5                       2300      2050     2100     2250     1100
55739  6                        400       250      200     5050     3000
65218  7                        500      1850     1750      650     5900
73685  8                       3100      4550     3800     1650        0
81044  9                       3000      6750     4600     1950     2000
88250  10                      5350      6800     5450        0        0
92985  11                      1850       300     1550      200     2050
111595 12                         0       150      150      100      150
118344 13                      2200      1850     2350      150      150
124245 14                       350        50       50     2500     2400
130458 15                      2400      1350     2300        0      100
135750 16                      1450      3100      900     1900     1600
147410 17                       100      1600     1700      600        0
156370 18                      1050        50       50     2050     1550
165741 19                         0      1150        0      950     1050
173757 20                      2200      1950     2200     2000      300
180716 21                         0       100       50     4600     3500
193143 22                      1600       100      600     3200     2400
202083 23                      1350       250      150        0      900
210466 24                      6900      7250     7650     7600     5550
217521 25                      6750     10450     9550     4900     2550
224085 26                      9600     12500     6500     2400       50
233692 27                      7600      7700     7400     6900     5550
245775 28                      5800      4900     5300     9100     2100
252977 29                      3400      2700     2700     7000     3700
259701 30                      7600      7700     7600     7000     5450
266246 31                      4900      2750     4700     9550     7300
271341 32                      2700        50        0    12700     2500
281309 33                      6900      6600     6900     7600     5050
286708 34                      9750      8350     9950     4600     2050

                                                                         ...  \
player_name                player_5 player_6 player_7 player_8 player_9  ...
tick   total_rounds_played                                               ...
1263   0                        150        0      150      100      150  ...
8696   1                        300        0      100      150      100  ...
18447  2                        900     2000     2500     1200     1950  ...
26997  3                       3550       50       50     2350       50  ...
35957  4                         50      200     1900       50     1000  ...
43304  5                       2050     1700      100     1850     2200  ...
55739  6                        150      950     1950      850     1800  ...
65218  7                       1350     2800     2500     2050     1100  ...
73685  8                        250      300        0     4150        0  ...
81044  9                       1550     2000     1900     6100     1900  ...
88250  10                       100       50       50     8450      150  ...
92985  11                         0      200     1600     4450      500  ...
111595 12                       150      100      150        0      150  ...
118344 13                      2050      100      250     2200       50  ...
124245 14                       100     2750     4000        0     3600  ...
130458 15                       650      250      600     2850      200  ...
135750 16                      1200     1850     2100     3400     1800  ...
147410 17                      2400      550      300     1100      100  ...
156370 18                       450     1450     2300     1450      700  ...
165741 19                         0     2750     3250      250      800  ...
173757 20                      1900     1100     3500     2550     3450  ...
180716 21                      2100     3700     2700     3000     2050  ...
193143 22                       800     2300     5400      100     5150  ...
202083 23                      1650        0      100      750     1750  ...
210466 24                      7300     7600     7600     5600     7600  ...
217521 25                      9750     4600     4600     5650     4400  ...
224085 26                      8000     1600     2400     8200     2200  ...
233692 27                      7600     7650     6900     7600     7300  ...
245775 28                      5200    10500     9200     5000     5500  ...
252977 29                      2800     8600    11800      850     8000  ...
259701 30                      7600     7650     7250     5150     7300  ...
266246 31                      4100     9450     5200     1550     9950  ...
271341 32                      1100    10300     2650     1050     9300  ...
281309 33                      6900     7800     7600     4350     7400  ...
286708 34                      8950     4800     4600     6300     4400  ...

                               name                                       \
player_name                player_1 player_10 player_2 player_3 player_4
tick   total_rounds_played
1263   0                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
8696   1                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
18447  2                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
26997  3                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
35957  4                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
43304  5                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
55739  6                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
65218  7                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
73685  8                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
81044  9                      Lucky  Ex3rcice  Graviti    mezii    ZywOo
88250  10                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
92985  11                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
111595 12                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
118344 13                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
124245 14                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
130458 15                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
135750 16                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
147410 17                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
156370 18                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
165741 19                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
173757 20                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
180716 21                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
193143 22                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
202083 23                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
210466 24                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
217521 25                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
224085 26                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
233692 27                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
245775 28                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
252977 29                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
259701 30                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
266246 31                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
271341 32                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
281309 33                     Lucky  Ex3rcice  Graviti    mezii    ZywOo
286708 34                     Lucky  Ex3rcice  Graviti    mezii    ZywOo


player_name                player_5 player_6 player_7 player_8 player_9
tick   total_rounds_played
1263   0                      Djoko     apEX   flameZ     Maka     ropz
8696   1                      Djoko     apEX   flameZ     Maka     ropz
18447  2                      Djoko     apEX   flameZ     Maka     ropz
26997  3                      Djoko     apEX   flameZ     Maka     ropz
35957  4                      Djoko     apEX   flameZ     Maka     ropz
43304  5                      Djoko     apEX   flameZ     Maka     ropz
55739  6                      Djoko     apEX   flameZ     Maka     ropz
65218  7                      Djoko     apEX   flameZ     Maka     ropz
73685  8                      Djoko     apEX   flameZ     Maka     ropz
81044  9                      Djoko     apEX   flameZ     Maka     ropz
88250  10                     Djoko     apEX   flameZ     Maka     ropz
92985  11                     Djoko     apEX   flameZ     Maka     ropz
111595 12                     Djoko     apEX   flameZ     Maka     ropz
118344 13                     Djoko     apEX   flameZ     Maka     ropz
124245 14                     Djoko     apEX   flameZ     Maka     ropz
130458 15                     Djoko     apEX   flameZ     Maka     ropz
135750 16                     Djoko     apEX   flameZ     Maka     ropz
147410 17                     Djoko     apEX   flameZ     Maka     ropz
156370 18                     Djoko     apEX   flameZ     Maka     ropz
165741 19                     Djoko     apEX   flameZ     Maka     ropz
173757 20                     Djoko     apEX   flameZ     Maka     ropz
180716 21                     Djoko     apEX   flameZ     Maka     ropz
193143 22                     Djoko     apEX   flameZ     Maka     ropz
202083 23                     Djoko     apEX   flameZ     Maka     ropz
210466 24                     Djoko     apEX   flameZ     Maka     ropz
217521 25                     Djoko     apEX   flameZ     Maka     ropz
224085 26                     Djoko     apEX   flameZ     Maka     ropz
233692 27                     Djoko     apEX   flameZ     Maka     ropz
245775 28                     Djoko     apEX   flameZ     Maka     ropz
252977 29                     Djoko     apEX   flameZ     Maka     ropz
259701 30                     Djoko     apEX   flameZ     Maka     ropz
266246 31                     Djoko     apEX   flameZ     Maka     ropz
271341 32                     Djoko     apEX   flameZ     Maka     ropz
281309 33                     Djoko     apEX   flameZ     Maka     ropz
286708 34                     Djoko     apEX   flameZ     Maka     ropz

[35 rows x 100 columns]

In [57]:
df = pd.read_csv('gamedata.csv')
# df = df.drop(columns=['steamid'])
suffix_list = [f"player_{i}" for i in range(1,11)]
df['player_name'] = df['name'].replace(dict(zip(list(df['name'].unique()),suffix_list)))
# df = df[['name','balance','kills_total','team_clan_name']]
df = df.pivot(index=['tick','total_rounds_played'], columns=['player_name'])
df.columns = ['_'.join(col) for col in df.columns.values]
df = df.to_csv('ithinkigotit.csv')
df

Create HLTV pipeline

In [ ]:
fetch("https://www.hltv.org/events/8229/iem-katowice-2025-play-in", {
  "headers": {
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "accept-language": "en-US,en;q=0.9",
    "priority": "u=0, i",
    "sec-ch-ua": "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "same-origin",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1"
  },
  "referrer": "https://www.hltv.org/events/archive",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});

In [ ]:
curl 'https://www.hltv.org/events/archive' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: en-US,en;q=0.9,en-IN;q=0.8' \
  -H 'cache-control: max-age=0' \
  -H 'cookie: FCNEC=%5B%5B%22AKsRol9RoeouGf-4-i8DVsuW-rT-zfEEEsffHJ1uGz2FF11_NN8uLu1m7IAocbXIXqxHHbLhgZfphUstMSjPWtr4o9Yz1htBXHagXmUbRr2daCROXg446NMmpPddLXRl8Zh_R2-_Jun6SRg9CfivgHDQ5UfOXPrSCA%3D%3D%22%5D%5D; MatchFilter={%22active%22:false%2C%22live%22:false%2C%22stars%22:1%2C%22lan%22:false%2C%22teams%22:[]}; CookieConsent={stamp:%274ZBjneINr7Sigs9KG1YoCDiBuKvkWpfJYJ8r794o4CWuPnQQIsVQfg==%27%2Cnecessary:true%2Cpreferences:true%2Cstatistics:true%2Cmarketing:true%2Cmethod:%27explicit%27%2Cver:1%2Cutc:1726679551262%2Cregion:%27us-18%27}; _fbp=fb.1.1727793354205.867162684962470655; _ia_loc_c=US; _ia_loc_r=IN; _au_1d=AU1D-0100-001727793355-6AYL6JB4-PAAK; _lc2_fpi=d138c12e9a9c--01j9484qw19gefp8b3asj3km7k; _lc2_fpi_meta=%7B%22w%22%3A1727793356673%7D; _pubcid=e15da282-7b3a-4b02-a80f-7ee333e51edc; _pubcid_cst=VyxHLMwsHQ%3D%3D; _cc_id=41a4387eab315db6cf372fb997ecc2cc; uuid=CDCA3571-E41D-4A95-A9AE-6CA31E43D9DD; _bc_int_ads_hltv.orgen_www.hltv.org=%7B%22visit%22%3A59%7D; _cc_id=41a4387eab315db6cf372fb997ecc2cc; bounceClientVisit6541=N4Igzg7gbiBcBmBDANmApgGhAEwJbbhAA4iAWAVlNIGYBGAdmoCYBOc8gNg6do5Cyj44DVqSK1aRavTFEWpLPCgAXYfSb168gAzkmWRAHs42rMgAOhABbLl5sAFJqAQQdMAYm-cQfAOivIylC+hgBOAOZe-CCIYCYC5jCw9FgEsDjRoYTRAMYqaqLiktRYYEKwtORY4TlZsEQcWAC28SDI+RXq8uJMTNoAvkA; _ga=GA1.1.368296785.1661008421; _sharedid=5c511425-73e1-44ab-aa9f-7627d296329f; _lr_env_src_ats=false; hb_insticator_uid=6635c464-9e8e-492c-9b20-93b256f8591d; showAdvancedScoreboard=true; _ga_FVWZ0RM4DH=GS1.1.1738350988.20.0.1738350988.60.0.0; __gads=ID=260c93463b41bf5c:T=1729481183:RT=1738426932:S=ALNI_MagWIpmB0p_A_TY3b5cRS4E3AxexQ; __gpi=UID=00000f46ca21438d:T=1729481183:RT=1738426932:S=ALNI_Macbx6sfFLRIt2e2XL2XqJpb9j0Bw; __eoi=ID=b5530ff8b6deb90d:T=1727793357:RT=1738426932:S=AA-AfjZEJc0e9C6zoNW8zWFxdV6z; __cf_bm=KMTg.zeEj.UKclGHBKJqq1f9y.7r9T8csjqTw99Md74-1738628970-1.0.1.1-lngqidL2FAAVnlJW03G6LbLiS9idxBvLXY6h3HB5vrgyhImC8nxs9T512RmIFQVPMhRwpDk4edbkolMtbkAA8Q; cf_clearance=ZSWSuRPWRjvWIHuEWU1kdBuGsQK6V3T7DnUM2DbUhuo-1738628973-1.2.1.1-l35VJEfaDONXC0Szs9x_qHs0mwwmjrARbUKH0YrCxYabyDEIyqQ0izXjUmuNisb.B3X6D9qad55nQEVWorCb9QUcBLv2tFwQE3A0xUyZsOeuVPY8rw.1THbMNznxZAGAXddziG51iR7MHpXPH6lMsm5nYbkEtbtmN_v9WzBxv5T6nah69t51oCGA9rOd66uKHaBcfZG9RNh6Fd2ShG5fZKPB0EuGVjLk_.w1NSfnlDrbcvVDc962ajGtXz9DKEqQSFdoPkQEx3A.i.1fAQBZBKY.GT9t8vSa6bKLYJicrrfiBniqHPs5D41nyair9GmalvakFuVbXv.RbRDiSW3Qtw; dicbo_id=%7B%22dicbo_fetch%22%3A1738628972299%7D; _lr_retry_request=true; _ga_525WEYQTV9=GS1.1.1738627953.89.1.1738629011.0.0.0; _sharedid_cst=kSylLAssaw%3D%3D; cto_bundle=pfevnF82cU1RZFYydUslMkI5MVpvSHJubEgxenc4Zm5pYzlmMnR6JTJGaUFlayUyQmR5JTJGYk1yMWJOUkNMOWlobllodGpRNnAwZ2NpZUREMHlIRzR2aWQ0ME5LcG5HcTdNS0lwZ0ZUR3F4T0NWWUhEUHZjSTNwSWZpRWoyWTVUa3lJbDNsZ2l1MFRH; cto_bundle=pfevnF82cU1RZFYydUslMkI5MVpvSHJubEgxenc4Zm5pYzlmMnR6JTJGaUFlayUyQmR5JTJGYk1yMWJOUkNMOWlobllodGpRNnAwZ2NpZUREMHlIRzR2aWQ0ME5LcG5HcTdNS0lwZ0ZUR3F4T0NWWUhEUHZjSTNwSWZpRWoyWTVUa3lJbDNsZ2l1MFRH; cto_bidid=owAjHF8yaHFZQyUyQjZMZnVDUXY2NVRtY0ltZEdRdnYyQ1VGTXhIWTlUZ3JCOHlCQ1hUeiUyQlMyRlBxY25pOXdQUU1HJTJGUTRISGpSQTRXWXZjYjFXV1p4UHd3R1pnZFY0YjN5QWsyTWRmeHExakZTZlJPTSUzRA; cto_bidid=owAjHF8yaHFZQyUyQjZMZnVDUXY2NVRtY0ltZEdRdnYyQ1VGTXhIWTlUZ3JCOHlCQ1hUeiUyQlMyRlBxY25pOXdQUU1HJTJGUTRISGpSQTRXWXZjYjFXV1p4UHd3R1pnZFY0YjN5QWsyTWRmeHExakZTZlJPTSUzRA; cto_dna_bundle=n5pcpl80M0RITmhlJTJCZkMwOUJGQlhaMUN2c3pXU3pnJTJCT2swQUhtQ0twWWp1ekVtWjB3Q1BXWGJDVzV4RzUzbUYxZSUyQlMlMkY' \
  -H 'priority: u=0, i' \
  -H 'referer: https://www.hltv.org/events' \
  -H 'sec-ch-ua: "Not A(Brand";v="8", "Chromium";v="132", "Microsoft Edge";v="132"' \
  -H 'sec-ch-ua-arch: "x86"' \
  -H 'sec-ch-ua-bitness: "64"' \
  -H 'sec-ch-ua-full-version: "132.0.2957.127"' \
  -H 'sec-ch-ua-full-version-list: "Not A(Brand";v="8.0.0.0", "Chromium";v="132.0.6834.111", "Microsoft Edge";v="132.0.2957.127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-model: ""' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-ch-ua-platform-version: "15.0.0"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0'

<Response [200]>
/matches/2378905/g2-vs-faze-iem-katowice-2025
/matches/2378906/eternal-fire-vs-3dmax-iem-katowice-2025
/matches/2378903/natus-vincere-vs-spirit-iem-katowice-2025
/matches/2378901/furia-vs-astralis-iem-katowice-2025
/matches/2378902/mouz-vs-liquid-iem-katowice-2025
/matches/2378904/gamerlegion-vs-the-mongolz-iem-katowice-2025
/matches/2378899/vitality-vs-faze-iem-katowice-2025
/matches/2378900/3dmax-vs-big-iem-katowice-2025
/matches/2378897/eternal-fire-vs-virtuspro-iem-katowice-2025
/matches/2378898/falcons-vs-g2-iem-katowice-2025
/matches/2378787/the-mongolz-vs-liquid-iem-katowice-2025
/matches/2378784/spirit-vs-astralis-iem-katowice-2025
/matches/2378785/natus-vincere-vs-furia-iem-katowice-2025
/matches/2378786/mouz-vs-gamerlegion-iem-katowice-2025
/matches/2378783/faze-vs-big-iem-katowice-2025
/matches/2378780/g2-vs-virtuspro-iem-katowice-2025
/matches/2378782/vitality-vs-3dmax-iem-katowice-2025
/matches/2378781/falcons-vs-eternal-fire-iem-katowice-2025
/matches/2378874/boss-vs-vagrants-esl-challenger-league-season-49-north-america
/matches/2378903/natus-vincere-vs-spirit-iem-katowice-2025
/matches/2378941/flyquest-red-vs-might-cct-season-2-north-america-series-4
/matches/2378909/eternal-fire-vs-faze-iem-katowice-2025
/matches/2378912/the-mongolz-vs-natus-vincere-iem-katowice-2025
/matches/2378992/aurora-vs-ninjas-in-pyjamas-cct-season-2-europe-series-18-closed-qualifier
/matches/2378908/liquid-vs-spirit-iem-katowice-2025
/matches/2378905/g2-vs-faze-iem-katowice-2025
/matches/2378906/eternal-fire-vs-3dmax-iem-katowice-2025
/matches/2378932/eclot-vs-alliance-european-pro-league-season-22
/matches/2378972/viperio-vs-genone-united21-league-season-26
/matches/2378907/gamerlegion-vs-astralis-iem-katowice-2025

In [ ]:
['/matches/2378695/pain-vs-astralis-iem-katowice-2025-play-in', '/matches/2378694/liquid-vs-wildcard-iem-katowice-2025-play-in', '/matches/2378696/virtuspro-vs-mibr-iem-katowice-2025-play-in', '/matches/2378697/big-vs-heroic-iem-katowice-2025-play-in', '/matches/2378693/wildcard-vs-furia-iem-katowice-2025-play-in', '/matches/2378686/complexity-vs-liquid-iem-katowice-2025-play-in', '/matches/2378690/eternal-fire-vs-heroic-iem-katowice-2025-play-in', '/matches/2378689/big-vs-imperial-fe-iem-katowice-2025-play-in', '/matches/2378687/flyquest-vs-astralis-iem-katowice-2025-play-in', '/matches/2378691/3dmax-vs-mibr-iem-katowice-2025-play-in', '/matches/2378692/pain-vs-gamerlegion-iem-katowice-2025-play-in', '/matches/2378688/virtuspro-vs-saw-iem-katowice-2025-play-in', '/matches/2378415/liquid-vs-heroic-iem-katowice-2025-play-in', '/matches/2378416/complexity-vs-eternal-fire-iem-katowice-2025-play-in', '/matches/2378422/imperial-fe-vs-furia-iem-katowice-2025-play-in', '/matches/2378421/wildcard-vs-big-iem-katowice-2025-play-in', '/matches/2378418/astralis-vs-mibr-iem-katowice-2025-play-in', '/matches/2378420/saw-vs-gamerlegion-iem-katowice-2025-play-in', '/matches/2378417/3dmax-vs-flyquest-iem-katowice-2025-play-in', '/matches/2378419/pain-vs-virtuspro-iem-katowice-2025-play-in', '/matches/2378907/gamerlegion-vs-astralis-iem-katowice-2025', '/matches/2378941/flyquest-red-vs-might-cct-season-2-north-america-series-4', '/matches/2378874/boss-vs-vagrants-esl-challenger-league-season-49-north-america', '/matches/2378903/natus-vincere-vs-spirit-iem-katowice-2025', '/matches/2378909/eternal-fire-vs-faze-iem-katowice-2025', '/matches/2378912/the-mongolz-vs-natus-vincere-iem-katowice-2025', '/matches/2378992/aurora-vs-ninjas-in-pyjamas-cct-season-2-europe-series-18-closed-qualifier', '/matches/2378908/liquid-vs-spirit-iem-katowice-2025', '/matches/2378905/g2-vs-faze-iem-katowice-2025', '/matches/2378906/eternal-fire-vs-3dmax-iem-katowice-2025', '/matches/2378932/eclot-vs-alliance-european-pro-league-season-22', '/matches/2378972/viperio-vs-genone-united21-league-season-26']